#!/bin/bash
# v109 — Mr.Long approve full audio fix (B60 fix + audio chain hardening)
# Adds: highpass 20Hz (DC blocker) + loudnorm 2-pass I=-16 TP=-1.5 + alimiter 0.5
# Generated by CMD THUC THI 30/6 17:20
set -e
cd "D:\DỰ ÁN AI\GIỌNG ĐỌC\DỰ ÁN TRUYỆN MA\SVHMP_Studio"

echo "=== CONCAT v109 với R94b silence bridge 1500ms ==="
ffmpeg -y -hide_banner -loglevel error \
  -i "output/ep_01/sections/hook.wav" \
  -i "output/ep_01/sections/setup.wav" \
  -i "output/ep_01/sections/incident.wav" \
  -i "output/ep_01/sections/reveal.wav" \
  -i "output/ep_01/sections/payoff.wav" \
  -i "output/ep_01/sections/cliffhanger.wav" \
  -f lavfi -i "anullsrc=r=22050:cl=mono:duration=1.5" \
  -filter_complex "[0:a][6:a][1:a][6:a][2:a][6:a][3:a][6:a][4:a][6:a][5:a]concat=n=11:v=0:a=1[v]" \
  -map "[v]" -c:a pcm_s16le -ar 22050 "output/ep_01/EP01_VOICE_v109.wav"

echo "=== MIX v109 (highpass 20Hz + alimiter 0.5 + loudnorm I=-16 TP=-1.5) ==="
ffmpeg -y -hide_banner -loglevel error \
  -i "output/ep_01/EP01_VOICE_v109.wav" \
  -i "D:/hdk_music_library/_episodes/ep_001/ep_001_full.mp3" \
  -filter_complex "[0:a]volume=0.92,highpass=f=20,alimiter=limit=0.5:attack=10:release=80,adelay=6000|6000[voice];[1:a]volume=0.282,afade=t=in:st=0:d=2.0[music];[voice][music]amix=inputs=2:duration=first:normalize=0,loudnorm=I=-16:TP=-1.5:LRA=11[out]" \
  -map "[out]" -c:a libmp3lame -q:a 2 -ar 44100 "output/ep_01/EP01_FULL_v109.mp3"

echo "=== DONE v109 ==="
