"""R94b/Tier 2.1 — Generate ffmpeg mix command from YAML config.

NO HARDCODED CONCAT — all parameters from bible/34_mix_config.yaml.
Auto-applies section silence bridge per R94b.

Usage:
  python tools/build_mix_command.py --version 102 --output-script run_v102.sh
  python tools/build_mix_command.py --version 102 --print
"""
import argparse
import sys
import yaml
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
CONFIG = BASE / "bible/34_mix_config.yaml"


def build_concat_command(cfg, version):
    sections = cfg["sections_order"]
    silence_ms = cfg["section_silence_ms"]
    silence_sec = silence_ms / 1000.0
    voice_wav = cfg["output"]["voice_wav"].replace("{version}", str(version))
    sr = cfg["output"]["sample_rate_voice"]

    # Build input list: 6 section WAVs + 1 silence source
    inputs = []
    for s in sections:
        inputs.append(f'-i "output/ep_01/sections/{s}.wav"')
    inputs.append(f'-f lavfi -i "anullsrc=r={sr}:cl=mono:duration={silence_sec}"')

    silence_idx = len(sections)  # 6 = silence input
    # Filter complex: [0][s][1][s][2][s][3][s][4][s][5]concat=n=11
    filter_parts = []
    for i, _ in enumerate(sections):
        filter_parts.append(f"[{i}:a]")
        if i < len(sections) - 1:
            filter_parts.append(f"[{silence_idx}:a]")
    n = len(filter_parts)
    filter_str = "".join(filter_parts) + f"concat=n={n}:v=0:a=1[v]"

    cmd = "ffmpeg -y -hide_banner -loglevel error "
    cmd += " ".join(inputs)
    cmd += f' -filter_complex "{filter_str}" -map "[v]" -c:a pcm_s16le -ar {sr} "{voice_wav}"'
    return cmd


def build_mix_command(cfg, version):
    vp = cfg["voice_pipeline"]
    mp = cfg["music_pipeline"]
    voice_wav = cfg["output"]["voice_wav"].replace("{version}", str(version))
    final_mp3 = cfg["output"]["final_mp3"].replace("{version}", str(version))
    sr_final = cfg["output"]["sample_rate_final"]
    q = cfg["output"]["mp3_quality"]
    intro_lead_ms = int(mp["intro_lead_sec"] * 1000)

    voice_filter = (
        f'[0:a]volume={vp["volume"]},'
        f'alimiter=limit={vp["alimiter_limit"]}:attack={vp["alimiter_attack_ms"]}:release={vp["alimiter_release_ms"]},'
        f'adelay={intro_lead_ms}|{intro_lead_ms}[voice]'
    )
    music_filter = (
        f'[1:a]volume={mp["volume"]},'
        f'afade=t=in:st=0:d={mp["fade_in_sec"]}[music]'
    )
    mix_filter = '[voice][music]amix=inputs=2:duration=first:normalize=0[out]'

    cmd = "ffmpeg -y -hide_banner -loglevel error "
    cmd += f'-i "{voice_wav}" -i "{mp["file"]}" '
    cmd += f'-filter_complex "{voice_filter};{music_filter};{mix_filter}" '
    cmd += f'-map "[out]" -c:a libmp3lame -q:a {q} -ar {sr_final} "{final_mp3}"'
    return cmd


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True, type=int)
    ap.add_argument("--config", default=str(CONFIG))
    ap.add_argument("--output-script", help="Write commands to .sh file")
    ap.add_argument("--print", action="store_true", help="Print commands to stdout")
    args = ap.parse_args()

    cfg_all = yaml.safe_load(Path(args.config).read_text(encoding="utf-8"))
    cfg = cfg_all["ep01_v_next"]

    concat_cmd = build_concat_command(cfg, args.version)
    mix_cmd = build_mix_command(cfg, args.version)

    # Validate R94b: silence count = sections_count - 1
    expected_boundaries = len(cfg["sections_order"]) - 1
    if cfg["audio_qa_thresholds"]["expected_boundaries_count"] != expected_boundaries:
        print(f"⚠️ Config inconsistency: expected_boundaries_count must equal {expected_boundaries}", file=sys.stderr)

    script = f"""#!/bin/bash
# Generated by build_mix_command.py v{args.version}
# R94b auto-applied: {cfg['section_silence_ms']}ms silence between {expected_boundaries} boundaries
set -e
cd "{BASE}"

echo "=== CONCAT v{args.version} với R94b silence bridge {cfg['section_silence_ms']}ms ==="
{concat_cmd}

echo "=== MIX v{args.version} (volume={cfg['voice_pipeline']['volume']} alimiter={cfg['voice_pipeline']['alimiter_limit']}) ==="
{mix_cmd}

echo "=== DONE ==="
"""

    if args.output_script:
        Path(args.output_script).write_text(script, encoding="utf-8")
        print(f"✓ Script: {args.output_script}")

    if args.print:
        print(script)


if __name__ == "__main__":
    main()
