"""R146 — Splice newly-rendered chunk WAV into existing section WAV.

Logic:
  1. Load section.wav (full)
  2. Load chunk timing offsets from spec (re-derive)
  3. Replace samples [chunk_start : chunk_end] with new_wav
  4. Save patched section.wav

NOTE: Requires section chunk boundaries metadata. Use simple approach:
  - Re-render entire section as fallback if metadata missing
  - For real splice need chunk_timestamps.json (generated by svhmp_v13_render.py)
"""
import sys
import argparse
import soundfile as sf
from pathlib import Path

BASE = Path(r"D:/DỰ ÁN AI/GIỌNG ĐỌC/DỰ ÁN TRUYỆN MA/SVHMP_Studio")
SECTIONS_DIR = BASE / "output/ep_01/sections"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--section", required=True)
    ap.add_argument("--chunk_idx", type=int, required=True)
    ap.add_argument("--new_wav", required=True)
    args = ap.parse_args()

    section_wav = SECTIONS_DIR / f"{args.section}.wav"
    new_wav = Path(args.new_wav)
    timestamps_file = SECTIONS_DIR / f"{args.section}_chunk_timestamps.json"

    if not section_wav.exists():
        print(f"ERROR: {section_wav} not found")
        sys.exit(1)
    if not new_wav.exists():
        print(f"ERROR: {new_wav} not found")
        sys.exit(1)

    print(f"=== PATCH AUDIO CHUNK ===")
    print(f"  Section: {args.section}")
    print(f"  Chunk idx: {args.chunk_idx}")
    print(f"  New WAV: {new_wav}")
    print()

    if not timestamps_file.exists():
        print(f"⚠️ Chunk timestamps file MISSING: {timestamps_file}")
        print("   Cannot splice without timing metadata.")
        print("   FALLBACK: Re-render entire section.")
        print()
        print(f"   cd C:/Users/Administrator/index-tts")
        print(f"   uv run --no-sync python {BASE}/tools/svhmp_v13_render.py \\")
        print(f"     --spec {SECTIONS_DIR}/spec_{args.section}.json \\")
        print(f"     --output {section_wav}")
        print()
        print(f"   TODO: Update svhmp_v13_render.py to emit chunk_timestamps.json")
        sys.exit(2)

    import json
    timestamps = json.loads(timestamps_file.read_text(encoding="utf-8"))
    if args.chunk_idx >= len(timestamps):
        print(f"ERROR: chunk_idx {args.chunk_idx} >= {len(timestamps)} chunks")
        sys.exit(1)

    chunk_start_sec = timestamps[args.chunk_idx]["start"]
    chunk_end_sec = timestamps[args.chunk_idx]["end"]

    full_audio, sr = sf.read(str(section_wav))
    new_audio, sr_new = sf.read(str(new_wav))
    assert sr == sr_new, f"Sample rate mismatch {sr} vs {sr_new}"

    start_idx = int(chunk_start_sec * sr)
    end_idx = int(chunk_end_sec * sr)

    patched = list(full_audio[:start_idx]) + list(new_audio) + list(full_audio[end_idx:])
    backup = section_wav.with_suffix(".wav.prepatch")
    section_wav.rename(backup)
    sf.write(str(section_wav), patched, sr, subtype="PCM_16")
    print(f"  ✓ Patched. Backup: {backup}")


if __name__ == "__main__":
    main()
